apiVersion: v1
kind: Service

metadata:
    name: movies-node-port-service
spec:
    type: NodePort
    selector:
        app: movies-service
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30008