apiVersion: apps/v1
kind: Deployment

metadata:
    name: movies-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: movies-service
    template:
        metadata:
            labels:
                app: movies-service
        spec:
            containers:
                - name: movies-service
                  image: jeffry322/movie-service:latest